BATCH_SIZE = 8
NUMBER_OF_CLASSES = 2
INPUT_SHAPE = (256, 256, 3)
LEARNING_RATE = 0.0001
EPOCHS = 150
WEIGHTS = 'imagenet'
AUGMENTATION_DATA = False
SAVE_MODEL_EVERY_EPOCH = False

MODEL_NAME = 'resnet18'

LOGS = 'logs'
SAVE_MODELS = 'save_models'
